### ISSUE TITLE
Bugs / no response in home app

### ISSUE THREAD

**Issue by BirbByte** [jinthagerman/homebridge-goldair-fan#3]
I've successfully added my fan & details into the config. I'm using the goldair sleepsmart pedestal fan (GCPF315).
The following code shows up when homebridge boots up:
```
(node:3988) UnhandledPromiseRejectionWarning: Error: resolveIds() timed out. Is the device powered on and the ID correct?
    at C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge-goldair-fan\node_modules\tuyapi\index.js:61:27
    at Timeout._onTimeout (C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge-goldair-fan\node_modules\p-timeout\index.js:19:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:3988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3988) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also it often shows the following in the log files:
```
[6/26/2020, 11:26:48 AM] [GCPF315] Getting current light status...
[6/26/2020, 11:26:48 AM] [GCPF315] Getting current SwingMode...
[6/26/2020, 11:26:48 AM] [GCPF315] Getting current active state...
[6/26/2020, 11:26:48 AM] [GCPF315] Getting current rotation speed...
```

**Comment by breadone** [comment]
same issue here. have you found a fix?

**Comment by HazardNZ** [comment]
also having the same issue

**Comment by jinthagerman** [comment]
sorry this plugin isn't really maintained anymore.
